catkin_ws/src/duckietown/launch/lane_controller.launch, catkin_ws/src/duckietown/launch/line_detector.launch
Sending a pull request for testing
=> fixing bug in lane_following.launch

catkin_ws/src/duckietown_msgs/msg/vehicleCoordination.msg
This is my first test with a branch but basically I just created a new message file for the output of the veh_coordinator. Just wanted to be sure that I don't mess up anything.
=> Coordination msgs

catkin_ws/src/ground_projection/launch/ground_projection.launch
the ground projection unit test will not work without this fix
=> typo in ground_projection

catkin_ws/src/spring2016/rkk/image_average_rkk/CMakeLists.txt, catkin_ws/src/spring2016/rkk/image_average_rkk/include/image_average_rkk/util.py, catkin_ws/src/spring2016/rkk/image_average_rkk/launch/image_average_node.launch, catkin_ws/src/spring2016/rkk/image_average_rkk/launch/image_average_test.launch, catkin_ws/src/spring2016/rkk/image_average_rkk/package.xml, catkin_ws/src/spring2016/rkk/image_average_rkk/setup.py, catkin_ws/src/spring2016/rkk/image_average_rkk/src/image_average_node.py, catkin_ws/src/spring2016/rkk/image_average_rkk/src/publisher_node.py, catkin_ws/src/spring2016/rkk/virtual_mirror_rkk/launch/virtual_mirror_raw_node.launch, catkin_ws/src/spring2016/rkk/virtual_mirror_rkk/launch/virtual_mirror_test.launch, catkin_ws/src/spring2016/rkk/virtual_mirror_rkk/launch/virtual_mirror_tester_node.launch
=> M02 rcdp rkk

catkin_ws/src/f23-LED/led_detection/include/led_detection/LEDDetector.py, catkin_ws/src/f23-LED/led_detection/scripts/unittests.py, catkin_ws/src/f23-LED/led_detection/src/LED_detector_node.py
Fast computation of cell-wise average brightness values
=> F23 fast downsampling

catkin_ws/src/duckietown/launch/vehicle_camera_detection_filter_control.launch, catkin_ws/src/vehicle_detection/src/vehicle_avoidance_control_node.py, catkin_ws/src/vehicle_detection/src/vehicle_detection_node.py, catkin_ws/src/vehicle_detection/src/vehicle_filter_node.py
@liampaull hey, this fixes the mega-merge from the point of view of f6. 
Let me know if anything looks weird.
FYI: I also nuked the vehicle filter and the distance check. If we see a vehicle we stop. It's faster like that and if it needs to run with the object detection it's better.
cc: @braraki @vdean @samcerq
=> F6 fix merge

catkin_ws/src/05-teleop/pi_camera/src/cam_info_reader_node.py, catkin_ws/src/10-lane-control/complete_image_pipeline/include/complete_image_pipeline/pipeline.py, catkin_ws/src/10-lane-control/ground_projection/include/ground_projection/GroundProjection.py, catkin_ws/src/10-lane-control/ground_projection/src/ground_projection_node.py, catkin_ws/src/10-lane-control/ground_projection/srv/EstimateHomography.srv, catkin_ws/src/10-lane-control/line_detector/src/line_detector_node.py, catkin_ws/src/40-coordination/led_emitter/src/led_emitter_node.py, dependencies_since_image.sh
Ground project python version not ready for primetime. 
However, making pr since I fixed several other breaking bugs.
=> Liam ground projection

catkin_ws/src/05-teleop/pi_camera/src/cam_info_reader_node.py, catkin_ws/src/10-lane-control/complete_image_pipeline/include/complete_image_pipeline/pipeline.py, catkin_ws/src/10-lane-control/ground_projection/include/ground_projection/GroundProjection.py, catkin_ws/src/10-lane-control/ground_projection/src/ground_projection_node.py, catkin_ws/src/10-lane-control/ground_projection/srv/EstimateHomography.srv, catkin_ws/src/10-lane-control/line_detector/src/line_detector_node.py, catkin_ws/src/40-coordination/led_emitter/src/led_emitter_node.py, dependencies_since_image.sh
I had to make a small change to the pipeline.py file to get the complete pipeline to even run
=> casting to int to prevent error

environment.sh
Resolved issue for "source environment.sh" that might happen when launching the ros remotely from laptop
=> add /bin/bash

catkin_ws/src/00-infrastructure/duckietown/include/duckietown_utils/constants.py, catkin_ws/src/00-infrastructure/duckietown/include/duckietown_utils/download.py, catkin_ws/src/00-infrastructure/duckietown/include/duckietown_utils/system_cmd_imp.py, catkin_ws/src/00-infrastructure/what_the_duck/include/what_the_duck/check_basic_dependencies.py, catkin_ws/src/00-infrastructure/what_the_duck/include/what_the_duck/checks/__init__.py, catkin_ws/src/00-infrastructure/what_the_duck/include/what_the_duck/checks/duckietown_dirs.py, catkin_ws/src/00-infrastructure/what_the_duck/include/what_the_duck/checks/environment_variable.py, catkin_ws/src/00-infrastructure/what_the_duck/include/what_the_duck/checks/existence.py, catkin_ws/src/00-infrastructure/what_the_duck/include/what_the_duck/checks/hostname.py, catkin_ws/src/00-infrastructure/what_the_duck/include/what_the_duck/checks/package_import.py, catkin_ws/src/00-infrastructure/what_the_duck/include/what_the_duck/checks/packages.py, catkin_ws/src/00-infrastructure/what_the_duck/include/what_the_duck/constant.py, catkin_ws/src/00-infrastructure/what_the_duck/include/what_the_duck/list_of_checks.py, catkin_ws/src/00-infrastructure/what_the_duck/include/what_the_duck/python_source_checks.py, catkin_ws/src/00-infrastructure/what_the_duck/include/what_the_duck/resolution.py, catkin_ws/src/00-infrastructure/what_the_duck/include/what_the_duck/sanity_checks.py, catkin_ws/src/00-infrastructure/what_the_duck/include/what_the_duck/statistics.py, catkin_ws/src/00-infrastructure/what_the_duck/include/what_the_duck/suite_git.py, catkin_ws/src/00-infrastructure/what_the_duck/include/what_the_duck/suite_ssh.py, catkin_ws/src/00-infrastructure/what_the_duck/include/what_the_duck/visualize.py, catkin_ws/src/10-lane-control/ground_projection/CMakeLists.txt
A better `what_the_duck`: less confusing, and it creates a file that can be given to TAs for debugging.
Workaround for #223 - see there for discussion.
=> what_the_duck + workaround for #223

Makefile, Makefiles/Makefile.log.mk, Makefiles/Makefile.openhouse.mk, catkin_ws/src/00-infrastructure/duckietown/config/baseline/intersection_control/open_loop_intersection_node/default.yaml, catkin_ws/src/00-infrastructure/duckietown/launch/make_log.launch, log_setup.sh
An easy way to log in a more minimal fashion
=> Liam logging devel

catkin_ws/src/10-lane-control/ground_projection/src/ground_projection_node.py, catkin_ws/src/10-lane-control/lane_control/scripts/lane_controller_node.py
Fixed an issue in GroundProjection where timestamp was zero after that node, really hard to find. Also added a variable to lane_control which contains the delay from image capture to the controller - useful (and necessary) for control design.
=> Fixed an issue which was necessary for control design

environment.sh
Improve logging output and add a time travel check.
=> Improve logging in environment.sh

catkin_ws/src/00-infrastructure/duckietown/config/baseline/lane_filter/lane_filter_node/default.yaml, catkin_ws/src/00-infrastructure/duckietown/config/baseline/pi_camera/cam_info_reader_node/kitt.yaml, catkin_ws/src/00-infrastructure/duckietown/config/baseline/pi_camera/cam_info_reader_node/megaman.yaml, catkin_ws/src/00-infrastructure/duckietown/config/baseline/pi_camera/cam_info_reader_node/oreo.yaml, catkin_ws/src/10-lane-control/lane_filter/src/lane_filter_node.py, catkin_ws/src/20-indefinite-navigation/apriltags_ros/signs_and_tags/tag_sizes.yaml, catkin_ws/src/70-convenience-packages/duckietown_demos/launch/master.launch
also merging the the cmd velocity sent to lane filter which should have been merged earlier.
=> fix for higher number april tag descriptions

catkin_ws/src/00-infrastructure/duckietown/config/baseline/stop_line_filter/stop_line_filter_node/default.yaml, catkin_ws/src/00-infrastructure/duckietown/launch/make_log.launch, catkin_ws/src/00-infrastructure/duckietown_msgs/msg/LanePose.msg, catkin_ws/src/10-lane-control/lane_control/scripts/lane_controller_node.easy_node.yaml, catkin_ws/src/10-lane-control/lane_control/scripts/lane_controller_node.py, catkin_ws/src/20-indefinite-navigation/stop_line_filter/src/stop_line_filter_node.py
=> Devel controllers manuelbre

catkin_ws/src/10-lane-control/ground_projection/include/ground_projection/GroundProjection.py
By accident I checked the order of the ground points instead of the received corner points in my last push.
=> Fix for homography problem

docker/env.sh, environment.sh
This fix is necessary to set the ROS_MASTER_URI correctly.
=> Fix error with ROS_MASTER_URI

docker/init_config_defaults.sh
this caused massive confusion and is not a good idea
=> removing copying default to hostname

catkin_ws/src/00-infrastructure/duckietown/config/baseline/traffic_light/traffic_light_node/default.yaml, catkin_ws/src/40-coordination/rgb_led/include/rgb_led/rgb_led.py, catkin_ws/src/40-coordination/traffic_light/src/traffic_light_node.py, requirements.txt
@AndreaCensi @tanij traffic light work with this now. The container to run is this one : duckietown/traffic-lights:master18
It uses as base duckietown/rpi-duckiebot-base:traffic-light18. When this is merged, built and push to duckietown/rpi-duckiebot-base:master18, I will make the change
=> made traffic light works

catkin_ws/src/00-infrastructure/duckietown/launch/core/line_detector.launch, catkin_ws/src/00-infrastructure/duckietown/launch/ground_projection.launch, catkin_ws/src/00-infrastructure/duckietown/launch/lane_controller.launch, catkin_ws/src/00-infrastructure/duckietown/launch/lane_filter.launch, catkin_ws/src/10-lane-control/ground_projection/launch/ground_projection.launch, catkin_ws/src/10-lane-control/lane_control/launch/lane_controller_node.launch, catkin_ws/src/10-lane-control/lane_filter/launch/lane_filter_node.launch, catkin_ws/src/10-lane-control/line_detector/launch/line_detector_node.launch, catkin_ws/src/20-indefinite-navigation/stop_line_filter/launch/stop_line_filter_node.launch
=> lane controller launch file update to not need machines file or drivers

catkin_ws/src/00-infrastructure/duckietown/launch/make_log.launch, catkin_ws/src/00-infrastructure/duckietown/launch/make_log_docker.launch
@liampaull 
Can you tell me if it is okay to rebuild and push the duckiebot-base and logging containers with master19 tag after this is merged?
=> topics for aido2 added

catkin_ws/src/01-interfaces/joy_mapper/src/joy_mapper_node.py, catkin_ws/src/01-interfaces/joy_mapper/src/joy_mapper_node2.py
As the function of the emergency stop was switched from toggle to clear states, this needs to be added to the joymapper node as well
=> Fix for joymapper node
